package com.deceval.auditoria.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InsertarLogAUDITORIAService", targetNamespace = "http://deceval.com/auditoria/services/", wsdlLocation = "file:/C:/NetBeansProjects/AUDITORIA/AUDITORIAServices/src/main/resources/InsertarLogAUDITORIAService.wsdl")

public class InsertarLogAUDITORIAService
    extends Service
{

    private final static URL INSERTARLOGAUDITORIASERVICE_WSDL_LOCATION;
    private final static WebServiceException INSERTARLOGAUDITORIASERVICE_EXCEPTION;
    private final static QName INSERTARLOGAUDITORIASERVICE_QNAME = new QName("http://deceval.com/auditoria/services/", "InsertarLogAUDITORIAService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/NetBeansProjects/AUDITORIA/AUDITORIAServices/src/main/resources/InsertarLogAUDITORIAService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INSERTARLOGAUDITORIASERVICE_WSDL_LOCATION = url;
        INSERTARLOGAUDITORIASERVICE_EXCEPTION = e;
    }

    public InsertarLogAUDITORIAService() {
        super(__getWsdlLocation(), INSERTARLOGAUDITORIASERVICE_QNAME);
    }

    public InsertarLogAUDITORIAService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INSERTARLOGAUDITORIASERVICE_QNAME, features);
    }

    public InsertarLogAUDITORIAService(URL wsdlLocation) {
        super(wsdlLocation, INSERTARLOGAUDITORIASERVICE_QNAME);
    }

    public InsertarLogAUDITORIAService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INSERTARLOGAUDITORIASERVICE_QNAME, features);
    }

    public InsertarLogAUDITORIAService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InsertarLogAUDITORIAService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InsertarLogAUDITORIAPort
     */
    @WebEndpoint(name = "insertarLogAUDITORIAService")
    public InsertarLogAUDITORIAPort getInsertarLogAUDITORIAService() {
        return super.getPort(new QName("http://deceval.com/auditoria/services/", "insertarLogAUDITORIAService"), InsertarLogAUDITORIAPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InsertarLogAUDITORIAPort
     */
    @WebEndpoint(name = "insertarLogAUDITORIAService")
    public InsertarLogAUDITORIAPort getInsertarLogAUDITORIAService(WebServiceFeature... features) {
        return super.getPort(new QName("http://deceval.com/auditoria/services/", "insertarLogAUDITORIAService"), InsertarLogAUDITORIAPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INSERTARLOGAUDITORIASERVICE_EXCEPTION!= null) {
            throw INSERTARLOGAUDITORIASERVICE_EXCEPTION;
        }
        return INSERTARLOGAUDITORIASERVICE_WSDL_LOCATION;
    }

}
