package com.deceval.auditoria.services;

import javax.jws.HandlerChain;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "insertarLogAUDITORIAPort", targetNamespace = "http://deceval.com/auditoria/services/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InsertarLogAUDITORIAPort {


    /**
     * 
     * @param parameter
     * @return
     *     returns com.deceval.auditoria.services.InsertarLogResponseType
     * @throws FaultMsg
     */
    @WebMethod(action = "insertarLog")
    @WebResult(name = "InsertarLogResponse", targetNamespace = "http://deceval.com/auditoria/services/xsd", partName = "parameter")
    public InsertarLogResponseType insertarLog(
        @WebParam(name = "InsertarLogRequest", targetNamespace = "http://deceval.com/auditoria/services/xsd", partName = "parameter")
        InsertarLogRequestType parameter)
        throws FaultMsg
    ;

}
